export const qandA = [
  {
    q: "What is the difference between a guard dog and a protection dog?",
    a: "You need to know the difference before you make a decision and buy a puppy. Think of it this way, a guard dog will guard your property and a protection dog will protect you and your family.A guard dog is trained specifically to be a working dog, not a pet. They are used as police dogs or military dogs and cannot turn off their training. Guard dogs can be trained to work at 3 distinct levels of security.Alarm Dog- This is a large breed with a deep, threatening bark. He will sound the alarm when someone approaches but will take action. In many cases, the alarm dogs bark is enough to deter unwanted visitors.Sentry Dog- A guard dog used as a sentry is most often used to guard the outside of a large property, such as a warehouse or shipyard. The dog is free to roam on his own without instruction from his owner. Because they are trained to attack anyone who trespasses, they are the best possible protection for this type of situation.Attack Dog- An attack-trained guard dog is trained to attack and even kill when given the command of his handler. These dogs were meant to be used as police K-9 or military service dogs. Dogs trained at this level are not sociable at any level and are not suitable as pets.Protection dogs are family dogs that will protect and defend their family in any situation they feel is threatening. Some of the most popular breeds for protection are Rottweilers, German Shepherds and Giant Schnauzers . The Doberman is the only working dog bred specifically as a protection dog. These breeds are extremely loyal and become true family members.They can be socialized with children and other pets, as well as other family, friends and neighbors. These dogs should never be trained specially to do what comes naturally to them. They should be bred with special consideration for their instinct to protect. These breeds do, however, need to be obedience trained and need to know their position in the family. They can be dominant, so it is important to establish your alpha role. Exercise is extremely important if you want to have a well-behaved, well-adjusted protection dog. These dogs need plenty of activity because they are big, physical animals with a lot of energy. The main distinction between a guard dog and a protection dogs is ultimately in the training. It is always best to seek a professional when you have determined what you need from your working companion.",
  },
  {
    q: "Are protection dogs safe?",
    a: "A well-trained protection dog is much safer than a dog that has had no training. This is because much like every human can punch, every dog can bite. However, a trained family protection dog understands right from wrong, and when biting is or is not allowed. A trained protection dog will understand that biting is only allowed when their handler permits them to do so, and will also reliably release on command. In contrast to this, an untrained dog will bite on impulse. If effectively trained and handled, a protection dog is very safe.",
  },
  {
    q: "If I buy a fully trained protection dog from EliteK9, will it be OK with my children, other pets and animals?",
    a: "Yes.Part of our matching process ensures that your dog will be OK with everyone in your household. Our personal protection dogs are raised in homes around children and conditioned to be loving and tolerant. We socialize and train our dogs with other animals including birds, horses, cats, rabbits and many more.",
  },
  {
    q: "Can you do any discounts on the prices for boarding and training our dog?",
    a: "We only do discounts for those who wish to train or buy more than one dog at a time . Raising dogs, boarding and training dogs take a lot of effort and time. This involves feeding and watering numerous dogs many times a day, bathing dogs, washing and cleaning kennels along with bowls and equipment also the toilet runs many times a day. Even trips to the vet if the need occurs.We often have to deflea and deworm the dogs that come to us and training them is a huge mental and physical work as well as responsibility and has taken more than 10 years of study and experience to gain the knowledge needed to be able to train all of the different types of dogs and breeds that are often brought to us (sometimes with behavioral issues) gaining both the knowledge and equipment needed to train the dogs coming to us has cost many thousands of pounds and still costs us up to this day to maintain and develop not to mention paying all of our staff.Unfortunately some fail to understand the amount of work and investment that goes into our profession to get the dogs up to standard and under the control of their handlers Finally to mention the risk taken by all of us dog trainers, decoys and other staff members who are needed to care for and train all of the dogs for security and protection, not to mention the dogs that come with unwanted aggression and possessive behaviors.",
  },
];
